### PR TITLE
OpenAPI spec file created for prayer-times API

### PR DESCRIPTION
**Pull request by tHeCh0s3n0n3**
Just a bit of background: 

I came across aladhan.com while starting to create an Android Wear app for prayer times. I was looking for an OpenAPI spec file to make interacting wit it easier. I found this bare repo. I figured I'd start things off (since I'm waiting for Suhur to roll around) and create a draft version.

API Methods specified: All

* [Prayer Times Calendar](https://aladhan.com/prayer-times-api#GetCalendar)
* [Prayer Times Calendar by address](https://aladhan.com/prayer-times-api#GetCalendarByAddress)
* [Prayer Times Calendar by city](https://aladhan.com/prayer-times-api#GetCalendarByCitys)
* [Prayer Times Hijri Calendar](https://aladhan.com/prayer-times-api#GetHijriCalendar)
* [Prayer Times Hijri Calendar by address](https://aladhan.com/prayer-times-api#GetHijriCalendarByAddress)
* [Prayer Times Hijri Calendar by city](https://aladhan.com/prayer-times-api#GetHijriCalendarByCity)
* [Timings](https://aladhan.com/prayer-times-api#GetTimings)
* [Timings By Address](https://aladhan.com/prayer-times-api#GetTimingsByAddresss)
* [Timings By City](https://aladhan.com/prayer-times-api#GetTimingsByCity) 
* [Current Date](https://aladhan.com/prayer-times-api#GetCurrentDate)
* [Current Time](https://aladhan.com/prayer-times-api#GetCurrentTime)
* [Current Timestamp](https://aladhan.com/prayer-times-api#GetCurrentTimestamp)
* [Prayer Times Methods](https://aladhan.com/prayer-times-api#GetMethods)

You should be able to copy and paste this file into the [Swagger.io editor](https://editor.swagger.io) to see and test the end result.

Potentially resolves issue #1

### CODE REVIEW

**Review by BilalIshtiaque — COMMENTED** [review]
Salaam!

JazakAllah Khair for your amazing help. I apologize having delayed reviewing this, it was because I wanted to set a standard for how we would construct this document and wanted to provide a base skeleton from which people can contribute and build upon.

As you can see, I have split the documentation into multiple yaml files and referencing them. Along with that, I am attaching tags to all apis that have similar functions (e.g. Get Date, Get Time, Get Timecard), etc.

And lastly, we're using redoc to generate a nice looking documentation that is human friendly, much nicer than swaggerUI imo!

Thus, I was hoping if u can adjust your PR to match the new format/skeleton we are going for. That way, it would be a lot easier to maintain and add stuff to, without the yaml file being a big blob.

Theres still a lot of APIs left that need documenting, so please do feel free to contribute to them, and the more u can split it across multiple PRs the better!

JazakAllah khair and please feel free to reach out if you have any questions.

**Comment by tHeCh0s3n0n3** [comment]
Salam Bilal,

Thank you for taking a look at the PR.

Duly noted. I believe I have a good idea of what you're going for.

Have a great day!

**Comment by tHeCh0s3n0n3** [comment]
Salam,

Done. Please have a look. Note that the description field doesn't accept $ref so I coped the description.md file's contents directly into the YAML file.

**Comment by BilalIshtiaque** [comment]
> Salam,
> 
> Done. Please have a look. Note that the description field doesn't accept $ref so I coped the description.md file's contents directly into the YAML file.

Walaikumassalam,

Soo, this was actually intended by design. If you want to download the openapi specification yaml file, then open the generated file in `./public/prayer-times.html` (that will be our public documentation) and download it from there:
image

That file is the single generated openapi spec u can use to import into postman, generate sdk, etc, the description reference will not cause problems there.

Thus, we can actually leave the description to be in the ref. Let me know if you are still not clear and I can elaborate further (:

**Comment by tHeCh0s3n0n3** [comment]
Thank you for clarifying.

The reason I included it directly is because according to the OpenAPI specification (OAS 3) [documentation on where `$ref` can be used](https://swagger.io/docs/specification/using-ref/) it states: "A common misconception is that `$ref` is allowed anywhere in an OpenAPI specification file. Actually $ref is only allowed in places where the [OpenAPI 3.0 Specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.3.md) explicitly states that the value may be a _reference_."

Looking at the specification for [`description`](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.3.md#rich-text-formatting), there is no mention that the `description` field's value can be a reference.

Therefore, `$ref` is not valid for use in the description and doing so would render the OpenAPI file invalid according to the OAS 3.

Since the intention is to have the description in a separate file for users to download, then having the description read something like the following will both serve the purpose and be valid according to the OAS 3:
_"A detailed description can be downloaded from [./public/prayer-times.html](#LINK_GOES_HERE)"_.

Thoughts?

CC: @BilalIshtiaque

**Comment by meezaan** [comment]
@tHeCh0s3n0n3 Al Salaamu alaykum. So your intent is to make all the files OAS3 compliant, yes?

**Comment by BilalIshtiaque** [comment]
@tHeCh0s3n0n3 thank you for sharing your insights, I think we can definitely talk more about what the best approach may be, I am actually completely fine with keeping the description within the yaml instead of using a ref.

@tHeCh0s3n0n3 @meezaan My vision has been this, but I would love to hear your thoughts on it:

We keep the documentation code as simple as possible and break it down as much as we can, with references everywhere (e.g. for description, examples, etc.)

That way, we can make is easy to make changes to, add/remove APIs and edit them whenever we need to.

That code is not necessarily OAS3 compliant directly. We can use redoc-cli to generate a nice looking UI, and it compiles all references and generates a OAS3 complaint document to download:
image

THAT document is what we can serve to the developers if they just want the swagger/openapi spec. We can add that document to the `public` folder.

But, by breaking our code down to more readable modules/format, it will be at least easier to work with.

Let me know your thoughts, anything works with me, but generally in my experience - I have had more success in breaking it down this way when working with large API sets.

JazakAllah khair for your efforts, looking forward to hearing feedback!

**Comment by meezaan** [comment]
@BilalIshtiaque yes let's pick this up on Discord or https://community.islamic.network.

**Pull request merged**
